// ════════════════════════════════════════════════════════════
//  TORO SENTAO — Datos del sitio (menú, testimonios, config)
//  Edita este archivo para actualizar precios y contenido
// ════════════════════════════════════════════════════════════

const TORO_DATA = {

  // ── Configuración general ───────────────────────────────
  config: {
    whatsapp:  "50760000000",       // ← Cambia por número real
    instagram: "https://instagram.com/torosentao",
    facebook:  "https://facebook.com/torosentao",
    maps:      "https://maps.google.com/?q=P9X7+4GJ,+Cuesta+de+Piedra,+Chiriquí,+Panamá",
    email:     "info@torosentao.com",
    telefono:  "+507 6000-0000",
  },

  // ── Menú ────────────────────────────────────────────────
  // Para agregar platos: copia un objeto y cambia los valores
  // "disponible": false  →  oculta el plato del menú
  menu: [
    {
      id: 1,
      categoria: "carnes",
      emoji: "🥩",
      nombre: "Puntas de Filete a la Leña",
      descripcion: "Corte premium nacional, marinado en especias chiricanas y asado lentamente sobre leña de mangle. El favorito de la casa.",
      precio: "18.50",
      etiqueta: "⭐ Favorito",
      badge: "🔥 Lo más pedido",
      disponible: true,
    },
    {
      id: 2,
      categoria: "carnes",
      emoji: "🍖",
      nombre: "Costillas BBQ Campesinas",
      descripcion: "Costillas de res tiernas, bañadas en salsa BBQ artesanal de guayaba y ají chombo. 6 horas de cocción lenta.",
      precio: "16.00",
      etiqueta: "Carnes",
      badge: "Lenta cocción",
      disponible: true,
    },
    {
      id: 3,
      categoria: "carnes",
      emoji: "🥓",
      nombre: "Corte del Día",
      descripcion: "Selección especial del carnicero según disponibilidad. Pregunta a tu mesero por el corte del día y su maridaje recomendado.",
      precio: "Consultar",
      etiqueta: "Especial",
      badge: "Varía cada día",
      disponible: true,
    },
    {
      id: 4,
      categoria: "carnes",
      emoji: "🫕",
      nombre: "Sancocho de Toro",
      descripcion: "Nuestro sancocho de carne de res con yuca, ñame, otoe y verduras frescas de la región. Tradición chiricana en un plato hondo.",
      precio: "10.00",
      etiqueta: "Tradicional",
      badge: "Sopa del día",
      disponible: true,
    },
    {
      id: 5,
      categoria: "acomps",
      emoji: "🍌",
      nombre: "Patacones Crujientes",
      descripcion: "Plátano verde aplastado y frito dos veces hasta lograr la textura perfecta. Servidos con hogao casero y aguacate de la región.",
      precio: "4.50",
      etiqueta: "Acompañamiento",
      badge: "Sin gluten",
      disponible: true,
    },
    {
      id: 6,
      categoria: "acomps",
      emoji: "🌿",
      nombre: "Yuca al Moho",
      descripcion: "Yuca hervida y luego sofrita con ajo, cebolla morada y culantro fresco. Una delicia del campo chiricano.",
      precio: "4.00",
      etiqueta: "Acompañamiento",
      badge: "Vegano",
      disponible: true,
    },
    {
      id: 7,
      categoria: "acomps",
      emoji: "🥗",
      nombre: "Ensalada de la Montaña",
      descripcion: "Ensalada fresca con lechuga, tomate, pepino, zanahoria rallada y aderezo de limón con hierbas locales. Fresca como el aire de Cuesta de Piedra.",
      precio: "5.00",
      etiqueta: "Acompañamiento",
      badge: "Fresca & local",
      disponible: true,
    },
    {
      id: 8,
      categoria: "acomps",
      emoji: "🍚",
      nombre: "Arroz con Guandú",
      descripcion: "Arroz blanco largo con guandú tierno, coco rallado y un toque de culantro. Acompañamiento clásico que nunca falla.",
      precio: "3.50",
      etiqueta: "Acompañamiento",
      badge: "Clásico",
      disponible: true,
    },
    {
      id: 9,
      categoria: "bebidas",
      emoji: "🥤",
      nombre: "Jugo Natural de Temporada",
      descripcion: "Preparado al momento con frutas de la región: maracuyá, piña, guanábana, tamarindo o naranja. Pregunta la disponibilidad del día.",
      precio: "3.00",
      etiqueta: "Bebida",
      badge: "100% natural",
      disponible: true,
    },
    {
      id: 10,
      categoria: "bebidas",
      emoji: "🍺",
      nombre: "Cerveza Bien Fría",
      descripcion: "Cerveza nacional o importada, perfecta para el clima fresco de la montaña. Balboa, Atlas, Heineken o Corona según disponibilidad.",
      precio: "2.50",
      etiqueta: "Bebida",
      badge: "Bien fría ❄️",
      disponible: true,
    },
    {
      id: 11,
      categoria: "bebidas",
      emoji: "☕",
      nombre: "Café de Boquete",
      descripcion: "Café de altura cultivado en las fincas del volcán Barú, servido en taza de barro. El mejor café del mundo, desde Chiriquí.",
      precio: "2.00",
      etiqueta: "Bebida",
      badge: "Origen Barú",
      disponible: true,
    },
    {
      id: 12,
      categoria: "bebidas",
      emoji: "🧃",
      nombre: "Agua de Pipa Fría",
      descripcion: "Agua de coco fresca directo de la pipa. Refrescante, natural e hidratante. Vendida mientras haya disponibilidad.",
      precio: "2.50",
      etiqueta: "Bebida",
      badge: "Refrescante",
      disponible: true,
    },
  ],

  // ── Testimonios ──────────────────────────────────────────
  // Para agregar más: copia un objeto al final del array
  testimonios: [
    {
      texto: "La mejor parada en la Ruta Sur. La carne tiene un sabor ahumado increíble y el servicio te hace sentir en casa. ¡Volveré el próximo fin de semana!",
      autor: "Carlos M.",
      lugar: "David, Chiriquí",
      estrellas: 5,
      inicial: "C",
    },
    {
      texto: "Un ambiente relajado, perfecto para ir en familia después de un paseo por Volcán. Los patacones con hogao son lo mejor que he comido en años.",
      autor: "Ana R.",
      lugar: "Panamá Ciudad",
      estrellas: 5,
      inicial: "A",
    },
    {
      texto: "Las puntas de filete a la leña son una obra maestra. El humo del mangle le da un sabor que ningún restaurante de ciudad puede replicar.",
      autor: "Jorge & Familia",
      lugar: "Santiago, Veraguas",
      estrellas: 5,
      inicial: "J",
    },
    {
      texto: "El café de Boquete al final de la comida fue la cereza del pastel. Servicio amable, precios justos y una vista espectacular. 10/10.",
      autor: "María L.",
      lugar: "Boquete, Chiriquí",
      estrellas: 5,
      inicial: "M",
    },
    {
      texto: "Pasamos por Cuesta de Piedra y nos detuvimos por recomendación de un amigo. ¡Qué descubrimiento! Las costillas BBQ son de otro nivel.",
      autor: "Roberto P.",
      lugar: "Costa Rica 🇨🇷",
      estrellas: 5,
      inicial: "R",
    },
    {
      texto: "El sancocho de toro es lo que necesitaba después de un día de senderismo en el Volcán Barú. Abundante, sabroso y reconfortante.",
      autor: "Laura & Diego",
      lugar: "Ciudad de Panamá",
      estrellas: 5,
      inicial: "L",
    },
  ],
};
      
